package com.grandhorizonrp.launcher;

import android.content.Context;

import org.json.JSONObject;

import java.io.File;
import java.io.FileOutputStream;
import java.io.OutputStreamWriter;
import java.nio.charset.StandardCharsets;

/**
 * Device-side session persistence (the launcher half of the persistence contract).
 *
 * WHAT is stored (app-private storage — no other app can read it):
 *   schema           persistence schema version (currently 1)
 *   kind             "guest" | "user"
 *   email            account e-mail (guest accounts use a generated @guest.ghrp.local address)
 *   guest_secret     guest account password — returned ONCE by the backend at
 *                    guest creation; lets this device re-auth (grant_type=password)
 *                    after the front_token expires. Never logged.
 *   front_token      last valid SSO token (TTL 12h; refreshed on every restore)
 *   account_name     SA-MP character name (server-authoritative, from the backend)
 *   account_uuid     stable account id ("acc-<id>")
 *   saved_at         epoch ms of the last successful save
 *
 * WHERE the character itself lives: on the SERVER (accounts.sex / accounts.skin /
 * launcher_char_created in the game database). This store only keeps the identity
 * needed to re-auth and look the character up. If the saved identity becomes
 * invalid, the launcher falls back to the WebView auth and, only then, character
 * creation re-appears.
 *
 * SECURITY: no passwords of registered users are ever stored (only the guest
 * secret, which is a random throwaway generated by the backend for this device).
 * Nothing here is written to logs.
 */
public final class SessionStore {
    private static final String FILE_NAME = "session.json";
    private static final int SCHEMA = 1;

    public static final class Session {
        public final String kind;
        public final String email;
        public final String guestSecret; // "" for registered users
        public String frontToken;
        public final String accountName;
        public final String accountUuid;
        public final long savedAt;

        Session(String kind, String email, String guestSecret, String frontToken,
                String accountName, String accountUuid, long savedAt) {
            this.kind = kind;
            this.email = email;
            this.guestSecret = guestSecret == null ? "" : guestSecret;
            this.frontToken = frontToken == null ? "" : frontToken;
            this.accountName = accountName == null ? "" : accountName;
            this.accountUuid = accountUuid == null ? "" : accountUuid;
            this.savedAt = savedAt;
        }

        public boolean isGuest() {
            return "guest".equals(kind);
        }
    }

    private SessionStore() {
    }

    private static File file(Context ctx) {
        return new File(ctx.getFilesDir(), FILE_NAME);
    }

    /** Atomically persist the session (temp file + rename). */
    public static void save(Context ctx, Session s) {
        try {
            JSONObject o = new JSONObject();
            o.put("schema", SCHEMA);
            o.put("kind", s.kind);
            o.put("email", s.email);
            o.put("guest_secret", s.guestSecret);
            o.put("front_token", s.frontToken);
            o.put("account_name", s.accountName);
            o.put("account_uuid", s.accountUuid);
            o.put("saved_at", System.currentTimeMillis());

            File tmp = new File(ctx.getFilesDir(), FILE_NAME + ".tmp");
            try (OutputStreamWriter w = new OutputStreamWriter(
                    new FileOutputStream(tmp), StandardCharsets.UTF_8)) {
                w.write(o.toString());
                w.flush();
            }
            //noinspection ResultOfMethodCallIgnored
            tmp.renameTo(file(ctx));
            GHRPLog.i("session saved (kind=" + s.kind + ", name=" + s.accountName + ")");
        } catch (Throwable t) {
            GHRPLog.e("session save failed", t);
        }
    }

    /** Refresh only the token (after a successful re-auth). */
    public static void updateToken(Context ctx, Session s, String newToken) {
        s.frontToken = newToken;
        save(ctx, s);
    }

    /** Load the saved session, or null when none exists / unreadable. */
    public static Session load(Context ctx) {
        try {
            File f = file(ctx);
            if (!f.exists() || f.length() == 0) return null;
            byte[] raw = java.nio.file.Files.readAllBytes(f.toPath());
            JSONObject o = new JSONObject(new String(raw, StandardCharsets.UTF_8));
            if (o.optInt("schema", 0) != SCHEMA) {
                GHRPLog.w("session schema mismatch — dropping");
                return null;
            }
            Session s = new Session(
                    o.optString("kind", "user"),
                    o.optString("email", ""),
                    o.optString("guest_secret", ""),
                    o.optString("front_token", ""),
                    o.optString("account_name", ""),
                    o.optString("account_uuid", ""),
                    o.optLong("saved_at", 0));
            if (s.email.isEmpty() || s.frontToken.isEmpty()) return null;
            return s;
        } catch (Throwable t) {
            GHRPLog.e("session load failed", t);
            return null;
        }
    }

    /** Drop the stored identity (logout / account reset). */
    public static void clear(Context ctx) {
        try {
            //noinspection ResultOfMethodCallIgnored
            file(ctx).delete();
            GHRPLog.i("session cleared");
        } catch (Throwable t) {
            GHRPLog.e("session clear failed", t);
        }
    }
}
